turtlebot2: #namespace
    
    n_actions: 4 # We have 3 actions, Forwards,TurnLeft,TurnRight,Backwards

    speed_step: 1.0 # Time to wait in the reset phases

    linear_forward_speed: 7.7 # Spwwed for ging fowards
    linear_turn_speed: 6.5 # Lienare speed when turning
    angular_speed: 6.7 # Angular speed when turning Left or Right
    max_steps_episode: 6000 # limitetion of number of steps.


    
    catch_reward: 1
    cooperative_catch_reward: 0.1
    time_penelty: -0.005
    robot_out_of_bounds_penalty: -0.5
    robot_hit_robot_penalty: -0.1
    max_x: 4.6
    max_y: 4.6
    min_x: -4.6
    min_y: -4.6
    goal_max_x: 1.5
    goal_min_x: -1.5
    goal_max_y: 1.5
    goal_min_y: -1.5
    catch_box: 1.5
    put_box_out: 4.5
    line_follower_and_object_crash: -1.5
    line_follower_and_object_disposer_crash: -1.5
    object_disposer_out_without_box: -1.5

 
    
    


    

